apiVersion: v2
appVersion: v1.11.6
description: A Helm chart for deploying cluster API.
icon: https://assets.unikorn-cloud.org/assets/images/logos/dark-on-light/icon.png
name: cluster-api-control-plane-kubeadm
type: application
version: 0.2.7
